# Generated by Django 2.0.5 on 2018-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashedLicensePlate', models.TextField(max_length=64)),
                ('serialNumber', models.TextField(max_length=128)),
                ('originCountry', models.TextField(max_length=64)),
            ],
        ),
    ]
