# Generated by Django 2.0.5 on 2018-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
