# Generated by Django 2.0.5 on 2018-05-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0002_auto_20180529_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='HashedLicensePlate',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
