# Generated by Django 2.0.5 on 2018-05-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0005_auto_20180529_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='HashedLicensePlate',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.TextField(default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
