# Generated by Django 2.0.5 on 2018-06-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0007_auto_20180605_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.UUIDField(default='', primary_key=True, serialize=False),
        ),
    ]
