# Generated by Django 2.0.5 on 2018-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0008_auto_20180618_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='originCountry',
            field=models.TextField(default='', max_length=2),
        ),
    ]
