# Generated by Django 2.0.5 on 2018-06-18 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0009_auto_20180618_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.TextField(default=uuid.UUID('cb76b9d3-a382-493b-82c0-4cdcdad47f3b'), primary_key=True, serialize=False),
        ),
    ]
