# Generated by Django 2.0.5 on 2018-06-18 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('europolapi', '0011_auto_20180618_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serialNumber',
            field=models.TextField(default=uuid.UUID('5bca5056-cae7-4a6f-a6c5-27b80760eb06'), max_length=64, primary_key=True, serialize=False),
        ),
    ]
